name: Publish to GitHub Container Repository
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        DOCKER_IMAGE: [superset-oauth] # Array: [superset,superset-oauth]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ghcr.io/${{ github.repository_owner }}/${{ matrix.DOCKER_IMAGE }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: Dockerfile.${{ matrix.DOCKER_IMAGE }}
