name: Get latest upstream revision
on:
  schedule:
    - cron:  '0 0 * * *' # Daily
jobs:
  get-revision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/apache/superset/branches/master | \
          jq ".commit" > superset-master.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -am "New upstream revision"
          git push