name: Get latest upstream revision
on:
  schedule:
    - cron:  '10 * * * *' # Every Hour
  workflow_dispatch:
jobs:
  get-revision:
    runs-on: ubuntu-latest
    outputs:
      modified: ${{ steps.git-check.outputs.modified }}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch upstream revision
        run: |
          curl -sL https://api.github.com/repos/apache/superset/branches/master | \
          jq ".commit" > superset-master.json
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "unchanged" || echo "true")
      - name: Commit latest upstream revision
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -am "New upstream revision"
          git push
  build:
    if: needs.get-revision.outputs.modified == 'true'
    needs: get-revision
    strategy:
      matrix:
        DOCKER_IMAGE: [superset-oauth] # Array: [superset,superset-oauth]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to GitHub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ghcr.io/${{ github.repository_owner }}/${{ matrix.DOCKER_IMAGE }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: Dockerfile.${{ matrix.DOCKER_IMAGE }}
